point to rebuilt cvs2git
the old one broke[1], and pointed to the volatile /software/bin/python;
this is made with explicit /software/bin/python-2.7.1

[1]
Traceback (most recent call last):
  File "/nfs/users/nfs_m/mca/gitwk-ext/cvs2svn/INST.230/software/python-2.5/bin/cvs2git", line 66, in <module>
    from cvs2svn_lib.main import git_main
  File "/software/python-2.5/lib/python2.5/site-packages/cvs2svn_lib/main.py", line 30, in <module>
  File "/software/python-2.5/lib/python2.5/site-packages/cvs2svn_lib/svn_run_options.py", line 40, in <module>
  File "/software/python-2.5/lib/python2.5/site-packages/cvs2svn_lib/svn_output_option.py", line 49, in <module>
  File "/software/python-2.5/lib/python2.5/site-packages/cvs2svn_lib/dumpfile_delegate.py", line 23, in <module>
  File "/software/python-2.5/lib/python2.5/md5.py", line 6, in <module>
    from hashlib import md5
  File "/software/python-2.5/lib/python2.5/hashlib.py", line 104, in <module>
    md5 = __get_builtin_constructor('md5')
  File "/software/python-2.5/lib/python2.5/hashlib.py", line 31, in __get_builtin_constructor
    import _md5
ImportError: No module named _md5